### ISSUE TITLE
关于数据集预处理问题

### ISSUE THREAD

**Issue by Mokuli** [YunjiePeng/OccludedGaitRecognition#1]
您好，我运行static_occlusion_filter_for_mapillary-vistas.py成功后，并未成功生成对应的遮挡转换为轮廓的文件，该如何生成呢

**Comment by YunjiePeng** [comment]
有具体报错信息吗？需要的话可以邮件单独联系我：yunjiepeng@buaa.edu.cn

**Comment by Mokuli** [comment]
大概是快速遍历了图片但是无法正常保存，早上修改了一下保存逻辑现在可以正常输出results的部分啦，谢谢您！

**Comment by YunjiePeng** [comment]
建议给我的这个邮箱yunjiepeng@buaa.edu.cn发个邮件，我应该能提供更多更直接的帮助:)
